trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'GCR'
    repository: 'stacyv-sandbox/azure'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    
