trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'GCR'
    repository: 'stacyv-sandbox/azure'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: nginx
    
- task: CopyFiles@2
  displayName: Copy Artifact
  inputs:
    Contents: 'deployment.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  displayName: Publish deployent.yaml artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
