apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: nginx
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/stacyv-sandbox/azure@sha256:64e341ca4f8ce60f2183dcd76a1c42e1e90fb24c3c77f23de429acbfc98cb207
        ports:
        - containerPort: 80
